language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run build

after_script:
  - git clone -b master "https://${GH_TOKEN}@${GH_REF}" master
  - rm -r master/*
  - cp -r public/. master/blog
  - cp index.html master/index.html
  - cd ./master
  - git config user.name "leezng"
  - git config user.email "im.leezng@gmail.com"
  - git add .
  - git commit -m "updated"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - dev

env:
  global:
    - GH_REF: github.com/leezng/leezng.github.io.git
    