language: node_js
node_js:
  - "iojs"
  - "7"

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm start generate

after_script:
  - cd ./public
  - git init
  - git config user.name "leezng"
  - git config user.email "leezng@163.com"
  - git add .
  - git commit -m "update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - dev

env:
  global:
    - GH_REF: github.com/leezng/leezng.github.io.git